### ISSUE TITLE
When I set migration to false, then still migration published.

### ISSUE THREAD

**Issue by devansh-webkul** [artkonekt/concord#13]
Hi,

**Issue:**
I have set my migration to false as you mentioned in the documentation.

In `concord/config.php` I have put my module name namespace with migration false. When I run vendor publish it stills publish the migration folder. May I know the reason why is this happening?

Or is there any global config from where I can set migration to false. Then automatically all migration's publishing stops.

**Version:**
1.7

**Comment by fulopattila122** [comment]
Setting the migrations to false
- doesn't prevent them from being published: https://laravel.com/docs/7.x/packages#publishing-file-groups
- but prevents them from being automatically registered: https://laravel.com/docs/7.x/packages#migrations

Since publishing is a manual process, it's in the developer's hand to control whether they want to publish it and/or to keep those migrations.

Actually, hiding the migrations requires them to be published somehow in the application, since modules typically rely on their own migrations. But if you publish them, you can make those migrations part of your application and modify them based on your needs.

See: https://konekt.dev/concord/1.7/migrations:
> If you turn the migrations off, they won't be visible for the artisan command.
>
> In such cases you can still publish the migrations. [...]

Also slightly related: vanilophp/framework#82

**Comment by devansh-webkul** [comment]
So, if I run `php artisan vendor:publish --all --force`, it will publish all migration. So it's not related to the config file. Because I have done what you say in your documentation and made my all modules migration false.

I need to prevent the migration files. Is there any feature which can prevent that?

**Comment by fulopattila122** [comment]
If you run `php artisan vendor:publish --all --force` it will run **ALL** the file groups of **ALL** the vendors.
Laravel in this case is doing exactly what you request from it, ie. publishing all the available files.

Instead, just tell Laravel which vendors' (use `--provider` switch) and which file groups (use `--tag` switch) do you want to be published. I think what you want is `php artisan vendor:publish --tag=config`.

Other examples:

```bash
# Publish all kinds of files from a specific vendor:
php artisan vendor:publish --provider="Maatwebsite\Excel\ExcelServiceProvider"

# Publish config only from a specific vendor:
php artisan vendor:publish --provider="Maatwebsite\Excel\ExcelServiceProvider" --tag=config

# Publish public assets from all vendors:
php artisan vendor:publish --tag=public

# Publish migrations from a specific vendor
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag=migrations
```

This is a Laravel feature, and there's nothing special about Concord here, it works the same way as any other external package. If you publish `--all --force` Laravel will publish ALL the files from ALL packages. It's up to you what do you instruct Laravel to do.

See also: https://konekt.dev/concord/1.7/publishing

**Comment by devansh-webkul** [comment]
Hi,

I am taking your example,
`php artisan vendor:publish --provider="Maatwebsite\Excel\ExcelServiceProvider"`

I have run this command. Still, it should publish all migrations. Well I have used your 1.2 version also in that migrations are not published when I ran `--all --force` but when I upgraded then things are changed. I don't want migration to be published.

Anyways thanks for the help, I will figure out what to do.

**Comment by devansh-webkul** [comment]
Hi,

I am pretty much sure that this problem is from your side. As I have not added any migration for publishing in my provider. And when I run command `php artisan vendor:publish`. Its still use your class method i.e. `Konekt\Concord\Conventions\ConcordDefault` `migrationsFolder()` method.
