### ISSUE TITLE
Question: stable release?

### ISSUE THREAD

**Issue by mkarnicki** [artkonekt/concord#3]
Hi,

I was having a look at Concord and found these two snippets:

> Note: Concord's first stable release is scheduled to October 2017.

> Note: Concord's first stable release (1.0) is scheduled to December 2017.

Is the stable release still planned for this month? Cheers.

**Comment by mkarnicki** [comment]
Haha you just replied elsewhere that it is ;). Closing!

**Comment by fulopattila122** [comment]
Yes. Actually there was no important change in the last couple of months so just about to finish docs and tag 1.0 this week. :)
