### ISSUE TITLE
 Target [Konekt\Concord\Contracts\Concord] is not instantiable.

### ISSUE THREAD

**Issue by enzonotario** [artkonekt/concord#4]
Hi!

I'm trying this package and everything works fine, but I notice that when I run `php artisan composer dump-autoload`, then it shows me an error and it don't allow me even run the server. The error is: `Target [Konekt\Concord\Contracts\Concord] is not instantiable.` and I think that is related to 
https://github.com/artkonekt/concord/blob/master/src/BaseServiceProvider.php#L66

Can you help me, please?

Thanks in advance!

**Comment by fulopattila122** [comment]
I think I already saw this problem back in the days.

Two questions:
- What Laravel version do you use?
- If it's < 5.5, do you have Concord added in [config/app.php](https://artkonekt.github.io/concord/#/installation?id=_2-register-the-provider-laravel-54-only)?

**Comment by enzonotario** [comment]
I'm using Laravel 5.7.. if I remove the concord module that I have added in `config/concord.php` and change the `BaseServiceProvider` to just the "original" `ServiceProvider`, I'm able to run `composer dump-autoload` without problems. Then I just revert the changes and, without running `composer dump-autoload` again, it works (until I run dump-autoload again)

**Comment by fulopattila122** [comment]
OK, I understand. What is the output of `php artisan concord:modules -a`?

**Comment by enzonotario** [comment]
it is:
```
enzo@enzo-ub ~/Code/backend $ php artisan concord:modules -a
+----+--------------+--------+---------+------------+---------------------------------+
| #  | Name         | Kind   | Version | Id         | Namespace                       |
+----+--------------+--------+---------+------------+---------------------------------+
| 1. | Price Module | Module | 0.0.1   | hawk.price | Hawk\Price\PriceServiceProvider |
+----+--------------+--------+---------+------------+---------------------------------+
```

**Comment by fulopattila122** [comment]
Do you have anything in your app's `AppServiceProvider::boot()` method?

**Comment by enzonotario** [comment]
mm In my `AppServiceProvider` I have the boot function but without content. I have removed the function and the error is still present.
In `PriceServiceProvider` I have:
```
<?php

namespace Hawk\Price;

use Hawk\Price\Eloquent\PriceList;
use Illuminate\Support\Facades\Event;
use Konekt\Concord\BaseModuleServiceProvider;
use Nuwave\Lighthouse\Events\BuildingAST;
use Nuwave\Lighthouse\Schema\Source\SchemaStitcher;

class PriceServiceProvider extends BaseModuleServiceProvider
{
    protected $models = [
        PriceList::class,
    ];

    /**
     * Perform post-registration booting of services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadMigrationsFrom(__DIR__ . '/Database/Migrations');

        if ($this->app->runningInConsole()) {
            $this->bootForConsole();

            if (! app()->environment('production')) {
                app(\Illuminate\Database\Eloquent\Factory::class)->load(__DIR__ . '/Factories');
            }
        }

        Event::listen(BuildingAST::class, function () {
            return (new SchemaStitcher(__DIR__ . '/Graphql/price.graphql'))->getSchemaString();
        });
    }

    /**
     * Register any package services.
     *
     * @return void
     */
    public function register()
    {
        $this->mergeConfigFrom(__DIR__.'/../config/price.php', 'price');
    }

    /**
     * Console-specific booting.
     *
     * @return void
     */
    protected function bootForConsole()
    {
        // Publishing the configuration file.
        $this->publishes([
            __DIR__.'/../config/price.php' => config_path('price.php'),
        ], 'price.config');
    }
}
```

anyways, I have tried with a plain `PriceServiceProvider` (without any implementation) and the error is still present. I mean:
```
<?php

namespace Hawk\Price;

use Hawk\Price\Eloquent\PriceList;
use Konekt\Concord\BaseModuleServiceProvider;

class PriceServiceProvider extends BaseModuleServiceProvider
{
    protected $models = [
        PriceList::class,
    ];
}
```

**Comment by fulopattila122** [comment]
Sorry, I mistyped, I'm looking for if `AppServiceProvider::register()` (instead of `boot()`) contains something

**Comment by enzonotario** [comment]
Yes, I have:
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{

    public function register()
    {
        \Gate::before(function ($user, $ability) {
           if ($user->isSuperAdmin()) {
               return true;
           }
        });

        if ($this->app->isLocal()) {
            $this->app->register(TelescopeServiceProvider::class);
        }
    }
    
}
```

but I also have tried leaving it blank, I mean:
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
}
```

**Comment by enzonotario** [comment]
hey, sorry! it was because I also have `Hawk\Price\PriceServiceProvider::class,` in my `config/app.php` (inside `providers`)...

I don't have to put it inside my providers?

**Comment by fulopattila122** [comment]
No, at the moment not. You need to add them to `config/concord.php` according to:
https://artkonekt.github.io/concord/#/creating-modules?id=creating-an-external-module-with-git-and-composer

Actually I want to change this, but since it is a BC, it will be part of v2.0:
https://github.com/artkonekt/concord/blob/9d7943ef6ea978685028a03ecaa23aca4786829b/README.md#plans-for-version-20

**Comment by enzonotario** [comment]
ok thanks so much and sorry for the issue!

**Comment by fulopattila122** [comment]
No worries, thanks for reporting, I'm actually happy about this thread.
It helps me to better understand how others are using it.
It also helps me to design the next major release which is mostly about simplification, and less deviation from Laravel common sense. There was no package auto discovery at the time Concord was born.

**Comment by enzonotario** [comment]
Sure! I think it would be nice to have a Slack to little issues (or questions) like this.. or if you don't have any problems, I'm sure I will be creating other issues (I just have arrived to this package and think it is awesome and I want to modularize some parts). But my english is so poor.. so maybe is better a chat? (if you can!)

**Comment by fulopattila122** [comment]
Github issues are perfectly fine for me 👌
