### ISSUE TITLE
Api Routes Not Found & Conflict between Web Routes & Api Routes

### ISSUE THREAD

**Issue by rawaf** [artkonekt/concord#6]
Hello, Attila Fulop

I really loved the concept of the Concord package to achieve the modularity and the extendability of our Laravel applications but after 4 days from the hard working to convert my Laravel boilerplate app to a Concord package, I faced a lot of problems and bugs because of the lack of the information in the documentation and I could solve the bugs by watching and tracing your modules and packages on Github. There is a lot of information should be included in the documentation, Please dig in deeper in the documentation with complete logical examples of code to demonstrate to the developers how to use Concord in a simple logical way.

My Laravel boilerplate app is similar to your Appshell box but my boilerplate consists of two main entities ( Admin Dashboard & Client API ). I turned my Admin Dashboard into a concord package successfully but I have two problems with my Client API.

1. When making a request to one of my API routes, my fallback route included in api.php responds with "Not Found" message.
- hint: I made a prefix for my API routes located in (app) RouteServiceProvider.php)
>  protected function mapApiRoutes()
    {
        Route::prefix('api/v1')
             ->middleware('api')
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }
- I supposed that my API routes dosen't registered but how my fallback route responds with "Not Found" message and below you will discover that fallback route responds instead of my web routes too.
- This is a snippet from config ->> box.php.
> 'routes' => [
    'files'     => ['web', 'api'],
    'prefix'    => null,
    'as'        => null,
]

2. Conflict between web.php and api.php routes.
I have a task resource route located in api.php for my task module targeting TaskController loctaed in ClientApi ->> TaskController.php and another one for web.php taregting Dashboard ->> TaskController
- Snippet from api.php route
> Route::apiResource('/tasks', 'ClientApi\TaskController');
- Snippet from web.php route
> Route::get('dashboard/tasks', 'Dashboard\TaskController@index')->name('tasks.index');
Route::get('dashboard/tasks/create', 'Dashboard\TaskController@create')->name('tasks.create');
Route::get('dashboard/tasks/{task}', 'Dashboard\TaskController@show')->name('tasks.show');
Route::post('dashboard/tasks', 'Dashboard\TaskController@store')->name('tasks.store');
Route::get('dashboard/tasks/{task}/edit', 'Dashboard\TaskController@edit')->name('tasks.edit');
Route::put('dashboard/tasks/{task}', 'Dashboard\TaskController@update')->name('tasks.update');
Route::delete('dashboard/tasks/{task}','Dashboard\TaskController@destroy')>name('tasks.destroy');
##### Now, The problem is if I tried to access eg: "http://localhost/dashboard/task" from my browser, the fallback route located in api.php responds with not found and if I commented  _Route::apiResource('/tasks', 'ClientApi\TaskController');_ every thing will working fine on dashboard, So I think there are a conflict between Api and Web routes.

I have another quick questions:
- Why you don't include Policies in your modules structure?
- Why you thinking about removing helpers in the next updates and if that happens will my app blew up after updating the Concord package to the new version?

Regards,

**Comment by rawaf** [comment]
I get resolved one of my problems which is API routes not found by removing the hardcoded API prefix in the kernel.php. I think the prefix of the routes located in config ->> box.php overrides the prefix of the routes located in the kernel.php. I think you should decouple the configuration of the api and web routes to allow the developer specifying a prefix to api routes different from web routes and vice-versa.

Thanks,

**Comment by fulopattila122** [comment]
Concord 1.3 was released a few days ago which adds support to multiple [route groups](https://artkonekt.github.io/concord/#/routes) like this:

```php
return [
    'modules' => [
        Vendor\MyBox\Providers\BoxServiceProvider::class => [
            'routes' => [
                [
                    'files'     => ['acl'],
                    'prefix'    => '/admin',
                    'as'        => 'admin.',
                    'middleware'=> ['web', 'auth', 'acl']
                ],
                [
                    'files'     => ['nonacl'],
                    'prefix'    => '/admin',
                    'as'        => 'admin.',
                    'middleware'=> ['web', 'auth']
                ]
            ]
        ]
    ]
];
```

Does this solve the problem you've described above?

**Comment by rawaf** [comment]
Yes, This is a perfect solution instead of my workaround by assigning the middleware to each group of routes in the web.php and api.php files. Sooner you will be hearing about an E-commerce & Logistics Orders package based on Concord modularity concept. Thanks
