### ISSUE TITLE
is there way to use concord with phpstorm auto complete?

### ISSUE THREAD

**Issue by seungmun** [artkonekt/concord#7]
No auto-complete and type-hints support for phpstorm?

ex)
UserProxy::_find_    <- static `find` not found.
function foo(...\Contracts\User $user) { return  $user->_posts_; }  <- relationship `posts` not found.

I don't want to define some relationship methods within Model and Contract both together.

huh?

**Comment by fulopattila122** [comment]
Does `User::find` autocomplete work with the plain Eloquent model?

**Comment by seungmun** [comment]
Absolutely it works with `User::find`.

**Comment by fulopattila122** [comment]
Ok, I'll add some annotations to the base class.

Btw if you're using it in an application the proxies are not necessary, they're just "locators" to be used by libraries.

**Comment by seungmun** [comment]
@fulopattila122 thanks :)
